spring:
  application:
    name: ai-trip-buddy-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_trip_buddy
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.6-flash

naver:
  maps:
    client-id: ${NAVER_MAPS_CLIENT_ID}
    client-secret: ${NAVER_MAPS_CLIENT_SECRET}

  api-hub:
    client-id: ${NAVER_API_HUB_CLIENT_ID}
    client-secret: ${NAVER_API_HUB_CLIENT_SECRET}