spring:
  application:
    name: ai-trip-buddy-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_trip_buddy
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash